export const ACTION = "ACTION";
export const FETCH_POKEMON_FAILURE = " FETCH_POKEMON_FAILURE";
export const FETCH_POKEMON_SUCCESS = " FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_REQUEST = " FETCH_POKEMON_REQUEST";
export const SET_COLOR = "SET_COLOR";
export const SET_POKELIST = "SET_POKELIST"; 
export const GET_POKELIST = "GET_POKELIST";
